apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: krakend_monitor

    scrape_configs:
      - job_name: krakend_scrapper
        scrape_interval: 5s
        metrics_path: '/metrics'
        static_configs:
          - targets:
              - 'krakend_service:8090'
            labels:
              app: krakend
